# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import docs_pb2 as docs__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in docs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDocument = channel.unary_unary(
                '/docs.DocumentService/CreateDocument',
                request_serializer=docs__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=docs__pb2.CreateDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/docs.DocumentService/GetDocument',
                request_serializer=docs__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=docs__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.EditDocument = channel.unary_unary(
                '/docs.DocumentService/EditDocument',
                request_serializer=docs__pb2.EditDocumentRequest.SerializeToString,
                response_deserializer=docs__pb2.EditDocumentResponse.FromString,
                _registered_method=True)
        self.SubscribeToUpdates = channel.unary_stream(
                '/docs.DocumentService/SubscribeToUpdates',
                request_serializer=docs__pb2.UpdateRequest.SerializeToString,
                response_deserializer=docs__pb2.DocumentUpdate.FromString,
                _registered_method=True)


class DocumentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=docs__pb2.CreateDocumentRequest.FromString,
                    response_serializer=docs__pb2.CreateDocumentResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=docs__pb2.GetDocumentRequest.FromString,
                    response_serializer=docs__pb2.GetDocumentResponse.SerializeToString,
            ),
            'EditDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.EditDocument,
                    request_deserializer=docs__pb2.EditDocumentRequest.FromString,
                    response_serializer=docs__pb2.EditDocumentResponse.SerializeToString,
            ),
            'SubscribeToUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToUpdates,
                    request_deserializer=docs__pb2.UpdateRequest.FromString,
                    response_serializer=docs__pb2.DocumentUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'docs.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('docs.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docs.DocumentService/CreateDocument',
            docs__pb2.CreateDocumentRequest.SerializeToString,
            docs__pb2.CreateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docs.DocumentService/GetDocument',
            docs__pb2.GetDocumentRequest.SerializeToString,
            docs__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docs.DocumentService/EditDocument',
            docs__pb2.EditDocumentRequest.SerializeToString,
            docs__pb2.EditDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/docs.DocumentService/SubscribeToUpdates',
            docs__pb2.UpdateRequest.SerializeToString,
            docs__pb2.DocumentUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
