# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: docs.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'docs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndocs.proto\x12\x04\x64ocs\">\n\x15\x43reateDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0finitial_content\x18\x02 \x01(\t\"7\n\x16\x43reateDocumentResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\"\"\n\x12GetDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"E\n\x13GetDocumentResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x03\"V\n\x13\x45\x64itDocumentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\x03\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x11\n\tedited_by\x18\x04 \x01(\x03\"F\n\x14\x45\x64itDocumentResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x1d\n\rUpdateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"S\n\x0e\x44ocumentUpdate\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x03\x12\x11\n\tedited_by\x18\x04 \x01(\x03\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xac\x02\n\x0f\x44ocumentService\x12K\n\x0e\x43reateDocument\x12\x1b.docs.CreateDocumentRequest\x1a\x1c.docs.CreateDocumentResponse\x12\x42\n\x0bGetDocument\x12\x18.docs.GetDocumentRequest\x1a\x19.docs.GetDocumentResponse\x12\x45\n\x0c\x45\x64itDocument\x12\x19.docs.EditDocumentRequest\x1a\x1a.docs.EditDocumentResponse\x12\x41\n\x12SubscribeToUpdates\x12\x13.docs.UpdateRequest\x1a\x14.docs.DocumentUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'docs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEDOCUMENTREQUEST']._serialized_start=20
  _globals['_CREATEDOCUMENTREQUEST']._serialized_end=82
  _globals['_CREATEDOCUMENTRESPONSE']._serialized_start=84
  _globals['_CREATEDOCUMENTRESPONSE']._serialized_end=139
  _globals['_GETDOCUMENTREQUEST']._serialized_start=141
  _globals['_GETDOCUMENTREQUEST']._serialized_end=175
  _globals['_GETDOCUMENTRESPONSE']._serialized_start=177
  _globals['_GETDOCUMENTRESPONSE']._serialized_end=246
  _globals['_EDITDOCUMENTREQUEST']._serialized_start=248
  _globals['_EDITDOCUMENTREQUEST']._serialized_end=334
  _globals['_EDITDOCUMENTRESPONSE']._serialized_start=336
  _globals['_EDITDOCUMENTRESPONSE']._serialized_end=406
  _globals['_UPDATEREQUEST']._serialized_start=408
  _globals['_UPDATEREQUEST']._serialized_end=437
  _globals['_DOCUMENTUPDATE']._serialized_start=439
  _globals['_DOCUMENTUPDATE']._serialized_end=522
  _globals['_ACK']._serialized_start=524
  _globals['_ACK']._serialized_end=558
  _globals['_DOCUMENTSERVICE']._serialized_start=561
  _globals['_DOCUMENTSERVICE']._serialized_end=861
# @@protoc_insertion_point(module_scope)
