# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import weather_pb2 as weather__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in weather_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeatherWorkerStub:
    """One analytics worker. Workers are independent gRPC servers; the
    coordinator is their client.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessBatches = channel.stream_stream(
                '/weather.WeatherWorker/ProcessBatches',
                request_serializer=weather__pb2.RecordBatch.SerializeToString,
                response_deserializer=weather__pb2.BatchAck.FromString,
                _registered_method=True)
        self.GetPartial = channel.unary_unary(
                '/weather.WeatherWorker/GetPartial',
                request_serializer=weather__pb2.AnalyticsRequest.SerializeToString,
                response_deserializer=weather__pb2.Partial.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/weather.WeatherWorker/Reset',
                request_serializer=weather__pb2.ResetRequest.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)


class WeatherWorkerServicer:
    """One analytics worker. Workers are independent gRPC servers; the
    coordinator is their client.
    """

    def ProcessBatches(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPartial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessBatches': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessBatches,
                    request_deserializer=weather__pb2.RecordBatch.FromString,
                    response_serializer=weather__pb2.BatchAck.SerializeToString,
            ),
            'GetPartial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPartial,
                    request_deserializer=weather__pb2.AnalyticsRequest.FromString,
                    response_serializer=weather__pb2.Partial.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=weather__pb2.ResetRequest.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.WeatherWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.WeatherWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherWorker:
    """One analytics worker. Workers are independent gRPC servers; the
    coordinator is their client.
    """

    @staticmethod
    def ProcessBatches(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/weather.WeatherWorker/ProcessBatches',
            weather__pb2.RecordBatch.SerializeToString,
            weather__pb2.BatchAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPartial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.WeatherWorker/GetPartial',
            weather__pb2.AnalyticsRequest.SerializeToString,
            weather__pb2.Partial.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.WeatherWorker/Reset',
            weather__pb2.ResetRequest.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WeatherCoordinatorStub:
    """The coordinator: receives replay streams, distributes batches to the
    workers, combines their partials, and answers analytics queries.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRecords = channel.stream_unary(
                '/weather.WeatherCoordinator/StreamRecords',
                request_serializer=weather__pb2.RecordBatch.SerializeToString,
                response_deserializer=weather__pb2.IngestSummary.FromString,
                _registered_method=True)
        self.GetAnalytics = channel.unary_unary(
                '/weather.WeatherCoordinator/GetAnalytics',
                request_serializer=weather__pb2.AnalyticsRequest.SerializeToString,
                response_deserializer=weather__pb2.AnalyticsReport.FromString,
                _registered_method=True)
        self.SubscribeUpdates = channel.unary_stream(
                '/weather.WeatherCoordinator/SubscribeUpdates',
                request_serializer=weather__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=weather__pb2.AnalyticsReport.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/weather.WeatherCoordinator/RegisterWorker',
                request_serializer=weather__pb2.RegisterRequest.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/weather.WeatherCoordinator/Reset',
                request_serializer=weather__pb2.ResetRequest.SerializeToString,
                response_deserializer=weather__pb2.Ack.FromString,
                _registered_method=True)


class WeatherCoordinatorServicer:
    """The coordinator: receives replay streams, distributes batches to the
    workers, combines their partials, and answers analytics queries.
    """

    def StreamRecords(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamRecords': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamRecords,
                    request_deserializer=weather__pb2.RecordBatch.FromString,
                    response_serializer=weather__pb2.IngestSummary.SerializeToString,
            ),
            'GetAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalytics,
                    request_deserializer=weather__pb2.AnalyticsRequest.FromString,
                    response_serializer=weather__pb2.AnalyticsReport.SerializeToString,
            ),
            'SubscribeUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeUpdates,
                    request_deserializer=weather__pb2.SubscribeRequest.FromString,
                    response_serializer=weather__pb2.AnalyticsReport.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=weather__pb2.RegisterRequest.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=weather__pb2.ResetRequest.FromString,
                    response_serializer=weather__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.WeatherCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('weather.WeatherCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherCoordinator:
    """The coordinator: receives replay streams, distributes batches to the
    workers, combines their partials, and answers analytics queries.
    """

    @staticmethod
    def StreamRecords(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/weather.WeatherCoordinator/StreamRecords',
            weather__pb2.RecordBatch.SerializeToString,
            weather__pb2.IngestSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.WeatherCoordinator/GetAnalytics',
            weather__pb2.AnalyticsRequest.SerializeToString,
            weather__pb2.AnalyticsReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/weather.WeatherCoordinator/SubscribeUpdates',
            weather__pb2.SubscribeRequest.SerializeToString,
            weather__pb2.AnalyticsReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.WeatherCoordinator/RegisterWorker',
            weather__pb2.RegisterRequest.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/weather.WeatherCoordinator/Reset',
            weather__pb2.ResetRequest.SerializeToString,
            weather__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
